Numpy

In [1]:
import numpy as np

In [8]:
x = np.arange(8)
print(x)

In [11]:
x = x.reshape(4,2)
print(x)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [13]:
# Declaring a matrix in Numpy as list
x= np.array([[0,1,2], [3,4,5],[6,7,8]])
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [20]:
# Reading from a csv file
x = np.genfromtxt("D:\\Personal\\Study\\Bits Pilani\\Git\\python-basic-1\\Matrix_Sample.csv",delimiter = ",", dtype="int8")
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [21]:
# 2D array of zeros
a = np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [23]:
# Np object properties
print(x.shape)
print(x.size)
print(x.ndim)
print(x.dtype)
print(x.itemsize)

(3, 3)
9
2
int8
1


In [24]:
# Changing data type of an array
x=np.array(x,dtype="int16")
print(x.dtype)

int16


In [25]:
# Copy object
xCpy = x
xCpy[0,0] = 99
print(xCpy)
print(x)

[[99  1  2]
 [ 3  4  5]
 [ 6  7  8]]
[[99  1  2]
 [ 3  4  5]
 [ 6  7  8]]


In [28]:
# Deep copy array - without reference
xCopy = x.copy()
xCopy[0][0] = 112
print(x)
print(xCopy)

[[99  1  2]
 [ 3  4  5]
 [ 6  7  8]]
[[112   1   2]
 [  3   4   5]
 [  6   7   8]]


Accessing Numpy array

In [30]:
x = np.arange(25).reshape(5,5)
print(x)
# Accessing by row*column 
print(x[2][4])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
14


In [31]:
# Accessing all value of a particular row
print(x[2,...])

[10 11 12 13 14]


In [32]:
# Accessing all value of a particular column
print(x[...,3])

[ 3  8 13 18 23]


In [36]:
# Access subset matrix
print(x[3:5,3:5])

[[18 19]
 [23 24]]


In [37]:
# Access a complete row
print(x[4])

[20 21 22 23 24]


Algebra

In [54]:
x = np.arange(9).reshape(3,3)
y = np.arange(9,18).reshape(3,3)
print(x)
print(y)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [42]:
# Addition of matrix
z = x + y
print(z)

[[ 9 11 13]
 [15 17 19]
 [21 23 25]]


In [43]:
# Substraction of matrix
z = x - y
print(z)

[[-9 -9 -9]
 [-9 -9 -9]
 [-9 -9 -9]]


In [44]:
# Dot product or multiplication of a Matrix
z= np.dot(x,y)
print(z)

[[  0  10  22]
 [ 36  52  70]
 [ 90 112 136]]


In [47]:
# Pseudo-Inverse of Matrix
z = np.linalg.pinv(x)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [49]:
# Identity Matrix
z = np.eye(3,3)
print(z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [55]:
# Eigen Value
z = np.linalg.eigvals(x)
print(z)

[ 1.33484692e+01 -1.34846923e+00 -1.15433316e-15]


In [53]:
# Algebra operations
s = np.array([2,4,6,8,10,12])
print(s)
print(np.mean(s))
print(np.median(s))
print(np.std(s))
print(np.var(s))


[ 2  4  6  8 10 12]
7.0
7.0
3.415650255319866
11.666666666666666
